# Generated by Django 3.0 on 2019-12-09 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Squirrel',
        ),
    ]
