# Generated by Django 3.0 on 2019-12-09 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20191209_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squirrels',
            old_name='shift',
            new_name='Shift',
        ),
    ]
